//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kunder()
        {
            this.Tildmeldings = new HashSet<Tildmelding>();
        }
    
        public int Id { get; set; }
        public string Navn { get; set; }
        public string Adresse { get; set; }
        public string Telefon { get; set; }
        public string RejseArrangementer { get; set; }
        public Nullable<int> Tilmelding { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tildmelding> Tildmeldings { get; set; }
    }
}
