//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rejsearrangementer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rejsearrangementer()
        {
            this.Tildmeldings = new HashSet<Tildmelding>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string By { get; set; }
        public Nullable<System.DateTime> Stardato { get; set; }
        public Nullable<System.DateTime> Slutdato { get; set; }
        public Nullable<int> Pris { get; set; }
        public string MaxAntal { get; set; }
        public string Beskrivelse { get; set; }
        public Nullable<int> Tilmelding { get; set; }
        public Nullable<int> Transportør { get; set; }
    
        public virtual Transportør Transportør1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tildmelding> Tildmeldings { get; set; }
    }
}
