//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VikingRejserEntities : DbContext
    {
        public VikingRejserEntities()
            : base("name=VikingRejserEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kunder> Kunders { get; set; }
        public virtual DbSet<Rejsearrangementer> Rejsearrangementers { get; set; }
        public virtual DbSet<Tildmelding> Tildmeldings { get; set; }
        public virtual DbSet<Transportør> Transportør { get; set; }
    }
}
